### ISSUE TITLE
Render Deployment guide

### ISSUE THREAD

**Issue by johnbeynon** [FlowiseAI/FlowiseDocs#5]
Hi there,

I'm contacting you from the Render support team.

We're getting a handful of support tickets into Render relating to deployments of Flowise following the guide at https://docs.flowiseai.com/deployment/render. 

At Render we use ephemeral disks (https://render.com/docs/disks) so a SQLlite database written to ~/.flowise is lost when new deploys are made, instance types changed, etc etc and consequently Flows are lost. The video on the guide page says that using a starter plan or above will keep the Flows active and saved -  It's true, the service won't sleep and provided nothing changes on the service then the flows would remain but any new deploys, or something that triggers the service to be restarted would mean the database is gone and flows lost. 

Adding a disk to the service (only possible for starter and above instance types) mounted to `/opt/render/.flowise` would prevent this behaviour and store the sqlite DB in a persistent location. Ideally this path could be user configurable via a environment variable but that's a nicety.

We'd appreciate a call out in the documentation to highlight this behaviour and workaround.

**Comment by HenryHengZJ** [comment]
thanks @johnbeynon for the suggestion!

In the latest v1.2.13 release, you can specify an env DATABASE_PATH. This will allow you to specify where the data is being stored. And using Render's Disk, you can mount that path and have persistent storage.

Also modified the docs here - https://docs.flowiseai.com/deployment/render#persistent-disk

**Comment by qicdvp** [comment]
@HenryHengZJ  Is there any fix for the same issue on azure???? Have tried to mount azure file share and failed multiple times.
Thanks so much!
